[[rules]]
description = "Generic API Key"
regex = '''(?i)apikey['"]?[=: ]['"]?[a-z0-9]{32,45}['"]?'''
tags = ["apikey"]

[[rules]]
description = "IP Address"
regex = '''\b(?:\d{1,3}\.){3}\d{1,3}\b'''
tags = ["ip"]

[[rules]]
description = "Token"
regex = '''(?i)token['"]?[=: ]['"]?[a-z0-9]{32,45}['"]?'''
tags = ["token"]

[[rules]]
description = "Private Key"
regex = '''-----BEGIN (RSA|DSA|EC|OPENSSH|PGP|PRIVATE) KEY-----'''
tags = ["key", "private"]

[[rules]]
description = "Email Address"
regex = '''[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'''
tags = ["email"]

[allowlist]
description = "Allowlist for known false positives"
files = [
  "example/allowed_file.txt",
  "example/allowed_directory/*"
]

[[rules]]
description = "High Entropy String"
regex = '''[a-zA-Z0-9/+]{40,}'''
entropy = 4.2
tags = ["entropy"]